### ISSUE TITLE
Specifying download path for files?

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-client#65]
The current version of the client downloads the files to the /downloads folder of the local machine, then searches for that folder, and copies the relevant file back. 

https://github.com/vanvalenlab/kiosk-client/blob/3222217389a03dbfde21375a8e9c61b1aac9a75c/kiosk_client/utils.py#L39

Is there a particular reason the client was set up this way? It seems like it would have been easier to just copy the input path and append a suffix to the file, so I'm wondering if there's some other technical reason that it was done this way.

**Comment by willgraf** [comment]
I configured it to download files to their `~/Downloads` directory in order to try to make it as portable and usable as possible.

> then [it] searches for that folder, and copies the relevant file back.

I'm not sure what this means. The files are processed and saved to the cloud bucket, then the client downloads the file to the downloads directory.

**Comment by ngreenwald** [comment]
Okay got it. So it wouldn't break anything if we added an optional output_path parameter that specifies where it gets saved?

**Comment by willgraf** [comment]
I don't think anything would break, but it is not currently supported.

**Comment by ngreenwald** [comment]
Okay great, we'll get started on that.

**Comment by omerbt** [comment]
Hi Will, I created a branch with this change. Could you authorize my account so that I can make a PR?
